<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.80.0" />
    <PackageReference Include="Grpc.AspNetCore.Web" Version="2.80.0" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf GrpcServices="Server" Include="Protos\metrics.proto" />
  </ItemGroup>

</Project>
