/* eslint-disable */
// @ts-nocheck

import * as jspbModule from 'google-protobuf';

var jspb = jspbModule;
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.metrics.EmptyRequest', null, global);
goog.exportSymbol('proto.metrics.MetricResponse', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data
 * @extends {jspb.Message}
 * @constructor
 */
proto.metrics.EmptyRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.metrics.EmptyRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.metrics.EmptyRequest.displayName = 'proto.metrics.EmptyRequest';
}

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data
 * @extends {jspb.Message}
 * @constructor
 */
proto.metrics.MetricResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.metrics.MetricResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.metrics.MetricResponse.displayName = 'proto.metrics.MetricResponse';
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  proto.metrics.EmptyRequest.prototype.toObject = function(opt_includeInstance) {
    return proto.metrics.EmptyRequest.toObject(opt_includeInstance, this);
  };

  proto.metrics.EmptyRequest.toObject = function(includeInstance, msg) {
    var f, obj = {};
    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

proto.metrics.EmptyRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.metrics.EmptyRequest;
  return proto.metrics.EmptyRequest.deserializeBinaryFromReader(msg, reader);
};

proto.metrics.EmptyRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};

proto.metrics.EmptyRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.metrics.EmptyRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

proto.metrics.EmptyRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};

if (jspb.Message.GENERATE_TO_OBJECT) {
  proto.metrics.MetricResponse.prototype.toObject = function(opt_includeInstance) {
    return proto.metrics.MetricResponse.toObject(opt_includeInstance, this);
  };

  proto.metrics.MetricResponse.toObject = function(includeInstance, msg) {
    var f, obj = {
      cpuUsage: jspb.Message.getFieldWithDefault(msg, 1, 0),
      memoryUsage: jspb.Message.getFieldWithDefault(msg, 2, 0),
      timestamp: jspb.Message.getFieldWithDefault(msg, 3, "")
    };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

proto.metrics.MetricResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.metrics.MetricResponse;
  return proto.metrics.MetricResponse.deserializeBinaryFromReader(msg, reader);
};

proto.metrics.MetricResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCpuUsage(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMemoryUsage(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTimestamp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};

proto.metrics.MetricResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.metrics.MetricResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

proto.metrics.MetricResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCpuUsage();
  if (f !== 0) {
    writer.writeInt32(1, f);
  }
  f = message.getMemoryUsage();
  if (f !== 0) {
    writer.writeInt32(2, f);
  }
  f = message.getTimestamp();
  if (f.length > 0) {
    writer.writeString(3, f);
  }
};

proto.metrics.MetricResponse.prototype.getCpuUsage = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};

proto.metrics.MetricResponse.prototype.setCpuUsage = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};

proto.metrics.MetricResponse.prototype.getMemoryUsage = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};

proto.metrics.MetricResponse.prototype.setMemoryUsage = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};

proto.metrics.MetricResponse.prototype.getTimestamp = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};

proto.metrics.MetricResponse.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};

export default proto.metrics;